package com.citywatch.entity;

import com.citywatch.enums.Role;
import com.citywatch.enums.TrustLevel;
import com.citywatch.enums.UserStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

@Entity
@Table(name = "users", indexes = {
    @Index(name = "idx_user_email", columnList = "email"),
    @Index(name = "idx_user_username", columnList = "username"),
    @Index(name = "idx_user_role", columnList = "role"),
    @Index(name = "idx_user_status", columnList = "status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * 12-char structured ID:  {STATE}{RTO}{TYPE}{7-digit-seq}
     * Examples:
     *   GJ05C0000001  — Gujarat, RTO-05, Citizen #1
     *   GJ05M0000001  — Gujarat, RTO-05, Moderator #1
     *   GJ05A0000001  — Gujarat, RTO-05, Admin #1
     * Generated by CwIdGenerator.nextUserId() before save.
     */
    @Id
    @Column(name = "id", length = 12, updatable = false, nullable = false)
    private String id;

    @Column(unique = true, nullable = false, length = 50)
    private String username;

    @Column(unique = true, nullable = false, length = 100)
    private String email;

    @Column(name = "password_hash", nullable = false)
    private String password;

    @Column(unique = true, length = 15)
    private String phone;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Role role;

    @Enumerated(EnumType.STRING)
    @Column(name = "trust_level", length = 20)
    @Builder.Default
    private TrustLevel trustLevel = TrustLevel.NORMAL;

    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    @Builder.Default
    private UserStatus status = UserStatus.ACTIVE;

    @Column(name = "strike_count")
    @Builder.Default
    private Integer strikeCount = 0;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "area_id")
    @com.fasterxml.jackson.annotation.JsonIgnore
    private Area area;

    @Column(nullable = false, length = 100)
    private String city;

    /** 2-letter Indian state code used in the ID, e.g. GJ, MH, DL */
    @Column(name = "state_code", length = 2)
    private String stateCode;

    /** 2-digit RTO district code used in the ID, e.g. 05, 12 */
    @Column(name = "rto_code", length = 2)
    private String rtoCode;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
}
